name: Build ESPP Manager

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Flutter Doctor
      run: flutter doctor -v
    
    - name: Clean Flutter
      run: flutter clean
    
    - name: Install dependencies
      run: |
        flutter pub get
        flutter pub deps
    
    - name: Generate Windows files
      run: flutter create --platforms=windows .
    
    - name: Build Windows App
      run: |
        flutter build windows --release --verbose
      continue-on-error: true
    
    - name: Check Build Output
      run: |
        dir build/windows/x64/runner/Release
      shell: cmd
      continue-on-error: true
    
    - name: Create Windows ZIP
      run: |
        cd build/windows/x64/runner/Release
        Compress-Archive -Path * -DestinationPath ../../../../../ESPP-Manager-Windows.zip
        cd ../../../../../
      if: success()
    
    - name: Upload Windows Build
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: ESPP-Manager-Windows.zip
        retention-days: 30
      if: success()
    
    - name: Upload Build Logs on Failure
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-logs
        path: |
          build/windows/**/*.log
          .dart_tool/flutter_build/**/*.log
        retention-days: 7
      if: failure()